# Generated by Django 4.1.1 on 2022-09-29 22:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_admin_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='basic_data',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='basic_data_admin', to=settings.AUTH_USER_MODEL),
        ),
    ]
