# Generated by Django 4.1.1 on 2022-09-29 23:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_admin_basic_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leader',
            name='basic_data',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='basic_data_leader', to=settings.AUTH_USER_MODEL),
        ),
    ]
